---
- name: Post odl-installation steps for all nodes
  hosts:
    - controller
    - compute
  sudo: yes
  tasks:
      #TODO(abregman): remove when bug 1334732 is resolved
      - name: Set selinux to permissive
        selinux: policy=targeted 
                 state=permissive

      - name: get ovs id
        shell: ovs-vsctl get Open_vSwitch . _uuid
        register: ovs_id

      # Setting local_ip to enable tunnelling
      - name: set local_ip
        command: "ovs-vsctl set Open_vSwitch {{ ovs_id.stdout }} other_config:local_ip={{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

      - name: Add public interface to public bridge
        shell: >
            sudo ovs-vsctl --no-wait -- --may-exist add-port br-ex eth2;
            sudo ip link set eth2 up

- name: Post odl-installation controller steps
  hosts: controller
  sudo: yes
  tasks:
      - name: Start neutron and nova services
        service: name={{ item }}
                 state=running
        with_items:
          - 'neutron-server'
          - 'neutron-dhcp-agent'
          - 'neutron-metadata-agent'
          - 'openstack-nova-scheduler'
          - 'openstack-nova-api'
          - 'openstack-nova-conductor'

      # Required for running tests
      - name: Create an external network
        quantum_network:
            state: present
            auth_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:35357/v2.0/"
            login_username: admin
            login_password: "{{ hostvars[inventory_hostname].admin_password | default('redhat') }}"
            login_tenant_name: admin
            name: "{{ installer.network.name }}"
            provider_network_type: "{{ installer.network.external.provider_network_type }}"
            provider_physical_network: "{{ installer.network.label }}"
            provider_segmentation_id: "{{ installer.network.external.vlan.tag|default(omit) }}"
            router_external: yes
            shared: no
            admin_state_up: yes

      - name: Create subnet for external network
        quantum_subnet:
            state: present
            auth_url: "http://{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}:35357/v2.0/"
            login_username: admin
            login_password: "{{ hostvars[inventory_hostname].admin_password | default('redhat') }}"
            login_tenant_name: admin
            tenant_name: admin
            network_name: "{{ installer.network.name }}"
            name: external-subnet
            enable_dhcp: False
            gateway_ip: "{{ provisioner.network.network_list.external.nested.subnet_gateway }}"
            cidr: "{{ provisioner.network.network_list.external.nested.subnet_cidr}}"
            allocation_pool_start: "{{ provisioner.network.network_list.external.nested.allocation_pool_start }}"
            allocation_pool_end: "{{ provisioner.network.network_list.external.nested.allocation_pool_end }}"

- name: Post odl-installation compute steps
  hosts: compute
  sudo: yes
  tasks:
      - name: Start nova services
        service: name='openstack-nova-compute'
                 state=running
