---
- name: Preparation tasks for unit tests
  hosts: controller
  gather_facts: yes
  roles:
    - component-test/set_facts
    - component-test/setup_env
    - component-test/repo
    - component-test/debug
