---
- name: Set fact for manage upgrade
  hosts: undercloud:overcloud
  gather_facts: false
  tasks:
    - name: set fact for disabled tempest when update is disabled
      set_fact: disabled_tempest=true
      when: installer.upgrade is defined and
            not installer.upgrade.enabled|bool

    - name: set fact for disabled scale if update disabled
      set_fact: disabled_scale=true
      when: installer.upgrade is defined and
            not installer.upgrade.enabled|bool

- include: repo-{{ product.name }}.yml
- include: upgrade-undercloud.yml
- include: upgrade-overcloud.yml
