---
- name: Create the upstream delorean repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean'][ansible_distribution][distro.full_version] }}/current/{{ product.repo.delorean.repo_file }}"
            dest=/etc/yum.repos.d/rdo-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean', 'delorean_mgt'] and product.repo.delorean_pin_version is not defined

- name: Create the upstream delorean dependency repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean'][ansible_distribution][distro.full_version] }}/{{ product.repo.delorean_deps.repo_file }}"
            dest=/etc/yum.repos.d/rdo-trunk-release-deps.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean', 'delorean_mgt'] and product.repo.delorean_deps is defined

- name: Create the pinned upstream delorean repositories for EPEL RDO
  get_url: url="{{ product.repo['delorean'][ansible_distribution][distro.full_version] }}/{{product.repo.delorean_pin_version}}/{{ product.repo.delorean.repo_file }}"
            dest=/etc/yum.repos.d/rdo-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean', 'delorean_mgt'] and product.repo.delorean_pin_version is defined

- name: make sure yum-plugin-priorities is installed
  yum: name='yum-plugin-priorities' state=present
  sudo: yes

- name: List available yum repositories
  command: yum -d 9 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines
