---
- name: Install rhosqe tests from source
  hosts: "{{ tester.host }}"
  gather_facts: no
  sudo: yes
  tasks:
    - yum: name=git state=present
    - git: repo={{ tester.git.repo }} version={{ tester.git.revision }}
           recursive=yes
           track_submodules=yes
           dest=~/{{ tester.dir }}

