---
- name: Install rpm deps for source-based tempest
  hosts: tester
  gather_facts: no
  sudo: yes
  tasks:
    - name: Install python-setuptools for easy_install
      yum: name=python-setuptools state=present

    - name: Install pip
      command: easy_install pip

    - name: Install devel packages for package build dependencies
      yum: name={{ item }} state=present
      with_items: "{{ tester.packages }}"

- name: Install tempest from source
  hosts: tester
  gather_facts: no
  tasks:
    - git: repo={{ tester.git.repo }} version={{ tester.git.revision | default('HEAD') }}
           dest={{ tester.dir }}
      register: tempest_repo
      when: tester.git.local_dir is not defined

    - synchronize: dest={{ tester.dir }} src={{ tester.git.local_dir }}/
                   archive=no recursive=yes perms=yes links=yes
      register: tempest_local_dir
      when: tester.git.local_dir is defined

    - command: chdir={{ tester.dir }} git log -1 --pretty=format:%h
      register: tempest_repo_version

    - debug: "msg='Build mark: tempest={{ tempest_repo_version.stdout }}'"

    - name: install virtualenv
      command: "python {{ tester.dir }}/tools/install_venv.py {{ tester.dir }}"
      when: tempest_repo|changed or tempest_local_dir|changed

    - name: Install extra pip requirements
      pip: name={{ item }} state=present virtualenv="~/{{ tester.dir }}/.venv"
      with_items: "{{ tester.pip_packages }}"
      when: tempest_repo|changed or tempest_local_dir|changed
