---
- include: pre-{{ tester.setup }}.yml

- name: collect controller facts for tempest configuration
  hosts: controller
  gather_facts: yes

- name: Configure tempest
  hosts: tester
  gather_facts: no
  sudo: no
  vars:
    deployer_input: "~/{{ tester.dir }}/etc/deployer-input-{{ product.version.code_name }}.conf"
  tasks:
    - name: Create a command to use tempest with our venv if needed
      copy:
        dest: "{{ tester.dir }}/with_venv"
        mode: 0755
        content: |
          #!/bin/bash
          cd "$(dirname $0)"
          [[ -d .venv ]] && source .venv/bin/activate
          exec "$@"

    - name: Create default RC file
      shell: echo "export OS_PASSWORD={{ hostvars[provisioner.nodes.controller.name].admin_password|default('redhat') }}" >> /tmp/defaultrc;

    - name: Add address to RC file
      shell: echo "export OS_AUTH_URL=http://{{ item }}:5000/v2.0" >> /tmp/defaultrc
      with_items:
          - "{{ hostvars[provisioner.nodes.controller.name].ansible_default_ipv4.address }}"
          - "{{ hostvars[provisioner.nodes.controller.name].ansible_default_ipv6.address }}"
      when: '"ansible_default" not in item'

    - stat: path={{ deployer_input }}
      register: deployer_input_path

    - template: dest={{ tester.dir }}/configure-tempest.sh src=../templates/configure-tempest.j2 mode=0755
      register: config_script

    - file: name={{ tester.dir }}/etc/tempest.conf state=absent
      when: config_script|changed

    - name: Configure tempest
      shell: >
          source {{ provisioner.rc_file | default('/tmp/defaultrc') }};
          {{ tester.dir }}/with_venv ./configure-tempest.sh
      args:
        creates: "~/{{ tester.dir }}/etc/tempest.conf"

    - name: Run testr init
      command: "{{ tester.dir }}/with_venv testr init"
      args:
        creates: "{{ tester.dir }}/.testrepository"

    - name: "Workaround: Cap boto version to 2.34 for RHOS5"
      pip: name=boto version=2.34 virtualenv={{ tester.dir }}/.venv chdir=~
      when: workarounds.lp1408987 is defined
