---
installer:
    overcloud_images: build
    images:
        '7-director':
            files:
                - no_op
        '8-director':
            files:
                - no_op
        'liberty':
            files:
                - no_op
        'mitaka':
            files:
                - no_op
        'master':
            files:
                - no_op
