---
- include: provision.yml
- include: install.yml
- include: test.yml

- name: Create Coverage Report
  hosts: openstack_nodes:!tester
  gather_facts: no
  sudo: yes
  roles:
      - { role: coverage/report, when: coverage is defined }
