---
- name: Create public network
  hosts: undercloud
  tasks:
      - name: Get pool name for creating public network with the same name
        sudo: yes
        shell: "grep -oP '(?<=default_floating_pool=)(.*$)' /etc/nova/nova.conf"
        register: pool_name

      - name: Get admin password
        register: get_admin_password_result
        shell: >
            grep 'OS_PASSWORD' {{ instack_user_home }}/overcloudrc | cut -d '=' -f2

      - name: Get auth url
        register: get_auth_url_result
        shell: >
            grep 'OS_AUTH_URL' {{ instack_user_home }}/overcloudrc | cut -d '=' -f2

      - name: Setup public network for floating ips
        register: public_network_uuid_result
        quantum_network:
            state: present
            auth_url: "{{ get_auth_url_result.stdout }}"
            login_username: admin
            login_password: "{{ get_admin_password_result.stdout }}"
            login_tenant_name: admin
            name: "{{ pool_name.stdout_lines|last }}"
            provider_network_type: "{{ hw_env.network_type }}"
            provider_physical_network: "{{ hw_env.physical_network }}"
            provider_segmentation_id: "{{ hw_env.ExternalNetworkVlanID }}"
            router_external: yes
            shared: no

      - name: Create subnet for external network net-iso
        quantum_subnet:
            state: present
            auth_url: "{{ get_auth_url_result.stdout }}"
            login_username: admin
            login_password: "{{ get_admin_password_result.stdout }}"
            login_tenant_name: admin
            network_name: "{{ installer.network.name }}"
            name: "{{ installer.network.name }}"
            enable_dhcp: False
            gateway_ip: "{{ hw_env.network_gateway }}"
            cidr: "{{ hw_env.floating_ip_cidr }}"
            allocation_pool_start: "{{ hw_env.floating_ip_start }}"
            allocation_pool_end: "{{ hw_env.floating_ip_end }}"

      - name: set fact for public network uuid
        set_fact:
            public_network_uuid: "{{ public_network_uuid_result.id }}"

      - name: reset external network mtu value initially set
        shell: >
            sudo ip link set {{ hw_env.vlan.external.device }} mtu {{ hw_env.vlan.external.mtu }}
        when: (hw_env is defined) and (hw_env.vlan.type == 'external')
